blank_issues_enabled: false
contact_links:
  - name: Questions & discussion
    url: https://github.com/PicoPlus-devel
    about: For questions, file sharing, or general discussion, please use these channels instead of opening an issue. Do not share ROMs.
